version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_N8N_API_URL=https://n8n.unit-y-ai.io/api/v1
      - REACT_APP_PLAYGROUND_API_URL=http://localhost:8000
    networks:
      - unityai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ui.unit-y-ai.io`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=cloudflare"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=unityai-network"

  # Development service with hot reload
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_N8N_API_URL=https://n8n.unit-y-ai.io/api/v1
      - REACT_APP_PLAYGROUND_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - unityai-network
    profiles:
      - dev

networks:
  unityai-network:
    external: true